## Learning Objectives

After reading, you should be able to :-

    1) Understand the difference between one-, two- and n-dimensional arrays in NumPy;

    2) Some basic function of Numpy

    3) Understand axis and shape properties for n-dimensional arrays.

Numpy is a python package.It stands for Numerical python.It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

#### Importing numpy

In [1]:
import numpy as np

#### ndarray

ndarray 'N dimensional array' describs the collection of items of same type.

In [2]:
## Creating 1-d array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
### More then one dimensional
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
## Upcasting
a = np.array([1,2,3,4.0])
a

array([1., 2., 3., 4.])

In [6]:
### provide dtype parameter
a = np.array([1,2,3],dtype = complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
### minimum dimensions parameter
np.array([1,2,3],ndmin = 3)

array([[[1, 2, 3]]])

### Array attributes / functions

#### 1) ndarray.shape

This attributes returns a tuple consiisting of array dimension. It can also be used to resize the array.

In [8]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.shape

(2, 3)

that means 2 rows and 3 columns

****resize the array with the help of np.shape****

In [10]:
a.shape = (3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 2) ndarray.resize

Numpy also provides a reshape functions to resize an array.

In [11]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a.resize(6,1)

In [13]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

#### 3) ndarray.itemsize

This array attribute returns the length of each element of array in bytes.

In [14]:
a = np.array([1,2,3.0])
a

array([1., 2., 3.])

In [15]:
a.itemsize

8

### Array Creation Routines

#### 1) numpy.zeros

It return a new array of specified size filled with zeros.

In [16]:
b = np.zeros(6)
b

array([0., 0., 0., 0., 0., 0.])

In [17]:
b = np.zeros((3,4,2))
b

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

#### 2) numpy.ones

It returns a new array of specified size and type , filled with one's.

In [18]:
c = np.ones(6)
c

array([1., 1., 1., 1., 1., 1.])

In [19]:
c = np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 3) numpy.eye

It return a new matrix/array of specified size and type of identity matrix/array.

In [20]:
I = np.eye(6)
I

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
type(I)

numpy.ndarray

In [22]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Creating array from existing data

##### 1) numpy.asarray

This function is similar to numpy.array except for the fact that it has fewer parameters.

In [26]:
## converting list to array
lt = [1,2,3,4,5]
a = np.asarray(lt)
a

array([1, 2, 3, 4, 5])

In [27]:
## If `dtype` is set, array is copied only if dtype does not match:
a = np.array([1, 2], dtype=np.float32)
np.asarray(a, dtype=np.float32) is a

True

In [28]:
np.asarray(a, dtype=np.float64) is a

False

In [30]:
### Converting from tuple
t = (1,2,3,4)
a = np.asarray(t)
a

array([1, 2, 3, 4])

#### 2) numpy.frombuffer

This function interprets a buffer as 1-D array any object hat exposes the buffer interface is used as parameter to return as ndarray.

In [34]:
s = b"Hello In The World Of Machine Learning"
a = np.frombuffer(s,dtype = 'S1')
a # 'b' stand for binary string

array([b'H', b'e', b'l', b'l', b'o', b' ', b'I', b'n', b' ', b'T', b'h',
       b'e', b' ', b'W', b'o', b'r', b'l', b'd', b' ', b'O', b'f', b' ',
       b'M', b'a', b'c', b'h', b'i', b'n', b'e', b' ', b'L', b'e', b'a',
       b'r', b'n', b'i', b'n', b'g'], dtype='|S1')

In [35]:
s = b'hello world'
np.frombuffer(s, dtype='S1', count=5, offset=6)

array([b'w', b'o', b'r', b'l', b'd'], dtype='|S1')

### Array From Numerical Range

##### 1) numpy.arange

This function return an ndarray object containing evenly spaced value with a given range.

In [37]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [39]:
# first parameter is staring point
# second parameter is ending point
# third parameter is separate 
np.arange(10,25,2)

array([10, 12, 14, 16, 18, 20, 22, 24])

##### 2) numpy.linspace

This function genrate number of evenly spaced value over the interval is specified.

numpy.linspace(start,stop,number,endpoint,retstep,dtype)

In [40]:
np.linspace(10,20,12)

array([10.        , 10.90909091, 11.81818182, 12.72727273, 13.63636364,
       14.54545455, 15.45454545, 16.36363636, 17.27272727, 18.18181818,
       19.09090909, 20.        ])

In [41]:
np.linspace(10,20,12,endpoint = False)

array([10.        , 10.83333333, 11.66666667, 12.5       , 13.33333333,
       14.16666667, 15.        , 15.83333333, 16.66666667, 17.5       ,
       18.33333333, 19.16666667])

In [42]:
np.linspace(10,20,12,endpoint = False,retstep = True)

(array([10.        , 10.83333333, 11.66666667, 12.5       , 13.33333333,
        14.16666667, 15.        , 15.83333333, 16.66666667, 17.5       ,
        18.33333333, 19.16666667]),
 0.8333333333333334)

#### 3) numpy.logspace

This function return an nd.array object that contain the number that are evenly spaced on a log scale.

In [43]:
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [44]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [45]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

##### 4) numpy.fromfunction

It is used for constructing an array by executing a function over each coordinate.

In [46]:
np.fromfunction(lambda i,j : i == j , (4,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False, False]])

In [47]:
np.fromfunction(lambda i,j : i**j , (4,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.],
       [1., 3., 9.]])

In [48]:
#Create a new 1-dimensional array from an iterable object.
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x0000022204A58EB0>

In [49]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

## np.array() v/s np.asarray() v/s np.asanyarray()

when we make numpy array using np.array than it would create a copy of the object array and would not reflect change to the original array.

On the other hand if we use np.asarray() then it would reflect change to the original array.

np.asanyarray() will try to convert array type object to array and if it is already an array type obejct to array and if it is already an array then it will try not to convert.

In [51]:
# for np.array()
l = [1,2,3,4]
a = np.array(l)
a

array([1, 2, 3, 4])

In [52]:
a[0] = 5
a

array([5, 2, 3, 4])

In [53]:
l

[1, 2, 3, 4]

In [57]:
# for np.asarray()
b = np.asarray(a)
b

array([5, 2, 3, 4])

In [59]:
b[0] = 7
b

array([7, 2, 3, 4])

In [60]:
a

array([7, 2, 3, 4])

In [61]:
# for np.asanyarray()
c = np.asanyarray(a)
c

array([7, 2, 3, 4])

In [62]:
type(c)

numpy.ndarray

In [63]:
d = np.asanyarray(l)
type(d)

numpy.ndarray

### Arithmetic operation

In [65]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
b = np.arange(3)
b

array([0, 1, 2])

In [69]:
## addition two array
np.add(a,b)

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [70]:
## subtraction two array
np.subtract(a,b)

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [71]:
## multiply two array
np.multiply(a,b)

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

In [72]:
## divide two array
np.divide(a,b)

<ipython-input-72-1f0bedb51eca>:2: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(a,b)
<ipython-input-72-1f0bedb51eca>:2: RuntimeWarning: invalid value encountered in true_divide
  np.divide(a,b)


array([[nan, 1. , 1. ],
       [inf, 4. , 2.5],
       [inf, 7. , 4. ]])

In [73]:
### power of array a raise to array b
np.power(a,b)

array([[ 1,  1,  4],
       [ 1,  4, 25],
       [ 1,  7, 64]], dtype=int32)

### Statistical functions using numpy

In [74]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
## minimum value
np.amin(a)

1

In [76]:
### maximum value
np.amax(a)

9

In [77]:
### return minimum value from each row
np.amin(a,1)

array([1, 4, 7])

In [78]:
### return minimum value from each column
np.amin(a,0)

array([1, 2, 3])

In [79]:
## median 
np.median(a)

5.0

In [80]:
## return median value from each column
np.median(a,0)

array([4., 5., 6.])

In [81]:
## return median value from each row
np.median(a,1)

array([2., 5., 8.])

In [82]:
### mean
np.mean(a)

5.0

In [83]:
## return mean value from each column
np.mean(a,0)

array([4., 5., 6.])

In [84]:
## return mean value from each row
np.mean(a,1)

array([2., 5., 8.])

### Sort in numpy

In [85]:
a = np.array([[3,7],[9,1]])
a

array([[3, 7],
       [9, 1]])

In [86]:
np.sort(a) ## row wise

array([[3, 7],
       [1, 9]])

In [88]:
np.sort(a,axis = 0) ## column wise

array([[3, 1],
       [9, 7]])

In [89]:
## Extract diagonal element from a array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
a.diagonal()

array([1, 5, 9])

### Shallow copy V/S deep copy

In [91]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
b = a ## shallow copy

In [93]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
b[0][2] = 10
b

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [95]:
a

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [96]:
b = a.copy() ## deep copy

In [97]:
b

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [98]:
b[0][2] = 3
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
a

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

Shallow copies duplicates as little as possible. A shallow copy of a collection is a copy of the collevtion is a copy of the collection structure not the element, with a shallow copy two collection now share the individual elements.

Deep copies  duplicates everything. A deep copy of a collection is two collection with all of the elements in the original collection duplicated.